# Generated by Django 3.2 on 2023-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
